version: '2.1'
services:
  backend:
    image: skuzzle/tally-backend:latest
    environment:
    - 'server.port=8080'
    - 'server.management.port=9000'
    - 'spring.data.mongodb.host=mongo'
  frontend:
    image: skuzzle/tally-frontend-server:latest
    ports:
    - '127.0.0.1:8080:8080'
    - '127.0.0.1:9000:9000'
    environment:
    - 'server.port=8080'
    - 'management.server.port=9000'
    - 'tally.backend.url=http://backend:8080'
    - 'tally.backend.healthUrl=http://backend:9000'
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:9000/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
  mongo:
    image: mongo
    volumes:
    - 'data:/data/db'
volumes:
  data:

