name: Build Branch
on: 
  push:
    branches-ignore: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Up JDK
      uses: actions/setup-java@v1
      with: 
        java-version: 13

    - name: Cache m2
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: maven-cache
          
    - name: Extract branch name
      id: extractBranch
      run: echo ::set-output name=branchName::${GITHUB_REF#refs/*/}
        
    - name: print build number
      run: echo Global Build Number is ${{ steps.extractBranch.outputs.branchName }}

    - name: Set maven build version
      run: mvn -B versions:set -DnewVersion=${{ steps.extractBranch.outputs.branchName }}

    - name: Build with maven
      run: mvn -B install

    - name: Containerize
      run: mvn -B -DskipTests=true jib:build -Ddocker=true -Ddeploy.username=${{ secrets.deploy_username }} -Ddeploy.password=${{ secrets.deploy_password }}

        #- name: Release maven package
        #  run: mvn -B deploy -s deploy-settings.xml -DskipTests -Ddeploy.username=${{ secrets.deploy_username }} -Ddeploy.password=${{ secrets.deploy_password }}
