name: Maven-CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set Up JDK
          uses: actions/setup-java@v1
          with: 
            java-version: 13
        
        - name: Generate build number
          uses: zyborg/gh-action-buildnum@v1
          with:
              gist_token: ${{ secrets.gist_token }}
              set_env: true

        - name: print build number
          run: echo Global Build Number is $BUILDNUM_FOR_GLOBAL
          
        - name: Increment version
          run: mvn -B versions:set -DnewVersion=$BUILDNUM_FOR_GLOBAL
        
        - name: Build with maven
          run: mvn -B install --file pom.xml
        
        - name: Release maven package
          uses: samuelmeuli/action-maven-publish@v1
          with:
              nexus_username:  ${{ secrets.nexus_username }}
              nexus_password: ${{ secrets.nexus_password }}
              gpg_private_key: ${{ secrets.gpg_private_key }}
              gpg_passphrase: ${{ secrets.gpg_passphrase }}
              maven_goals_phases: "deploy"
